# Generated by Django 4.2.11 on 2024-03-07 23:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("master_data", "0001_initial"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    """
                        CREATE TABLE IF NOT EXISTS "master_data"."city" (
                            id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                            province_id UUID NOT NULL REFERENCES "master_data"."province" ON DELETE CASCADE ON UPDATE CASCADE,
                            name VARCHAR(100) NOT NULL,
                            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                        );
                    """
                )
            ],
            reverse_sql=[
                (
                    """
                        DROP TABLE IF EXISTS "master_data"."city";
                    """
                )
            ],
        )
    ]
